#server:
  #port: 18087
#spring:
  #application:
    #name: gateway-discovery
  #cloud:
    #nacos:
      #discovery:
        #server-addr: 127.0.0.1:8848
      #config:
        #server-addr: 127.0.0.1:8848
        #file-extension: yaml
        #extension-configs[0]:
          #data-id: gateway.yml
          #group: DEFAULT_GROUP
          #refresh: true
    #gateway:
      #httpclient:
        # 连接超时时间，单位：毫秒
        #connect-timeout: 2000
        # 服务响应时间：90秒
        #response-timeout: 90s
      # 全局跨域处理
      #globalcors:
        # 处理url映射，即options请求被拦截
        #add-to-simple-url-handler-mapping: true
        #cors-configurations:
          #'[/**]':
            # 放行所有域；也可以设置为具体值，如：- "http://localhost:18084"、- "http://localhost:18086"
            #allowedOrigins: '*'
            # 放行所有请求方式；也可以设置为具体值，如：- "GET"、- "POST"、- "PUT"、- "DELETE"、- "OPTIONS"
            #allowedMethods: '*'
            # 放行所有请求头；也可以设置为具体值，如：- "Accept"、- "Authorization"
            #allowedHeaders: '*'
            # 放行携带认证体：为true时，allowedOrigins的值就不能为'*'，否则Credentials就不能在响应求头上返回
            #allowCredentials: true
            # 最大有效期，单位：毫秒
            #maxAge: 90000
      #routes[0]:
        # 路由id：自定义，但要保持唯一性
        #id: gateway-provider
        # nacos服务名称，即{spring.application.name}；lb为load Balance
        #uri: http://localhost:18086
        #uri: lb://gateway-provider
        #predicates[0]:
          # 路由过滤器
          #name: Path
          # API地址匹配
          #args[pattern]: /nacos/**
        #filters:
          # 过滤器：去掉前缀，即请求/nacos/echo/，实际是请求/echo/
          #- StripPrefix=1
      #routes[1]:
        #id: nacos-config
        #uri: lb://nacos-config
        #predicates[0]:
          #name: Path
          #args[pattern]: /nacosConfig/**
        #filters:
          # 过滤器：增加前缀，即请求/nacos/echo/，实际是请求/api/nacos/echo/
          #- PrefixPath=/api

