server:
  port: 17070

spring:
  application:
    name: config-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    config:
      server:
        git:
          uri: https://gitee.com/dongxinliu/config_discovery_demo.git
          search-paths: /
          #search-paths: '{application}'
          # 解决 org.springframework.cloud.config.server.environment.NoSuchLabelException: No such label: main
          default-label: master
