server:
  port: 18082

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: seata-storage
  main:
    allow-bean-definition-overriding: true
  datasource:
    name: storageDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seata?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    druid:
      max-active: 20
      min-idle: 2
      initial-size: 2

seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: ${spring.application.name}-tx-group
  config:
    type: nacos
    nacos:
      serverAddr: 127.0.0.1:8848
      dataId: seata-server.yml
      #username: nacos
      #password: nacos
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      #username: nacos
      #password: nacos